export PATH=/Applications/android-sdk/platform-tools:/Applications/XAMPP/bin:/usr/local/share/npm/bin:/Users/brandon/Dropbox/Work/scripts:$PATH
export EDITOR=/bin/subl
export PATH=$PATH:$HOME/.caffeine